config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @tasks = Task.all
    end

    def new
        @task  = Task.new
    end

    def create 
        @task = Task.new(task_params)

        if @task.save
            redirect_to tasks_path
        else
            render 'new'
        end
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params)
        redirect_to tasks_path
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_path
    end


    private 
        def task_params
            params.require(:task).permit(:title, :description)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= form_for(@task) do |f| %>
    <div><%= f.label :title %></div>
    <div><%= f.text_field :title %></div>

    <div><%= f.label :description %></div>
    <div><%= f.text_field :description %></div>

    <div><%= f.submit %></div>
<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<table>
    <thead>
        <tr>
            <td>タスク名</td>
            <td>説明</td>
        </tr>
    </thead>

    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= task.title %></td>
            <td><%= task.description %></td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'New', new_task_path %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= form_for(@task) do |f| %>
    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', tasks_path %>